### PR TITLE
Don't build PRs with only docs.

### PR DESCRIPTION
**Pull request by calavera**
Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Yay!

**Comment by thaJeztah** [comment]
ping @fredlf @jamtur01 @moxiegirl @SvenDowideit just FYI; docs-only PRs will no longer be build, so a huge timesaver!

**Comment by calavera** [comment]
hopefully :wink:

**Comment by moxiegirl** [comment]
I get that everyone is happy that docs-only won't build the whole suite. But we do need to build the docs themselves. Seriously.

**Comment by icecrime** [comment]
@moxiegirl I'm pretty sure that building docs was never part of the CI test campaign (as appears by checking a build output such as [this one](https://jenkins.dockerproject.com/job/Docker-PRs/8854/console)): I don't think we're loosing anything with this, only saving resources. So no worries, Jess and David were right to merge this themselves!

That being said, if you need docs to be built during CI, it shouldn't be hard to setup.

**Comment by jfrazelle** [comment]
yes we can work on this and gettinng the api stuff I was showing you too ;)

**Comment by moxiegirl** [comment]
@icecrime @jfrazelle Just after I commented this I found a PR that a contributor had not run `make docs` on.  It is pretty annoying to be fixing builds someone else broke.    It seems like adding a `make docs` in there should be relatively easy. I would have done the work to learn to do it myself but I'm maxed out at the moment.  

@jfrazelle I'd like to fix this pretty quick. So, can we get this done this week? The api stuff is a nice-to-have in my book.

**Comment by jfrazelle** [comment]
ya I can do this this week

On Mon, Jun 1, 2015 at 9:00 AM, moxiegirl <notifications@github.com> wrote:

> @icecrime <https://github.com/icecrime> @jfrazelle
> <https://github.com/jfrazelle> Just after I commented this I found a PR
> that a contributor had not run make docs on. It is pretty annoying to be
> fixing builds someone else broke. It seems like adding a make docs in
> there should be relatively easy. I would have done the work to learn to do
> it myself but I'm maxed out at the moment.
>
> @jfrazelle <https://github.com/jfrazelle> I'd like to fix this pretty
> quick. So, can we get this done this week? The api stuff is a nice-to-have
> in my book.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/leeroy/pull/15#issuecomment-107607139>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by moxiegirl** [comment]
Thanks @jfrazelle much appreciated.

**Pull request merged**
